// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJj2P6b8stQNJRu8GjAn4dOVbYsVANV4',
    appId: '1:215763026208:web:04a70688e28356764ad745',
    messagingSenderId: '215763026208',
    projectId: 'teacher-manager-app-e25b4',
    authDomain: 'teacher-manager-app-e25b4.firebaseapp.com',
    storageBucket: 'teacher-manager-app-e25b4.firebasestorage.app',
    measurementId: 'G-G8L8TVLYZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7Q8pi-HbfqLud7jn0T9DxCWSWZVhUP8',
    appId: '1:215763026208:android:58b553d3266e3f5b4ad745',
    messagingSenderId: '215763026208',
    projectId: 'teacher-manager-app-e25b4',
    storageBucket: 'teacher-manager-app-e25b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9ESJw1P48hAh5eVZBL2D55wbo0H83ps',
    appId: '1:215763026208:ios:4f04ea941355e5494ad745',
    messagingSenderId: '215763026208',
    projectId: 'teacher-manager-app-e25b4',
    storageBucket: 'teacher-manager-app-e25b4.firebasestorage.app',
    iosBundleId: 'com.example.flutterSchoolproject',
  );
}
